;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


;;;SWIG wrapper code starts here
(in-package #:cl-matrix)
(cl:defmacro defanonenum (cl:&body enums)
  "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cffi:defcfun ("cublasInit" cublasInit) :pointer)

(cl:export 'cublasInit)

(cffi:defcfun ("cublasShutdown" cublasShutdown) :pointer)

(cl:export 'cublasShutdown)

(cffi:defcfun ("cublasGetError" cublasGetError) :pointer)

(cl:export 'cublasGetError)

(cffi:defcfun ("cublasGetVersion" cublasGetVersion) :pointer
  (version :pointer))

(cl:export 'cublasGetVersion)

(cffi:defcfun ("cublasAlloc" cublasAlloc) :pointer
  (n :int)
  (elemSize :int)
  (devicePtr :pointer))

(cl:export 'cublasAlloc)

(cffi:defcfun ("cublasFree" cublasFree) :pointer
  (devicePtr :pointer))

(cl:export 'cublasFree)

(cffi:defcfun ("cublasSetKernelStream" cublasSetKernelStream) :pointer
  (stream :pointer))

(cl:export 'cublasSetKernelStream)

(cffi:defcfun ("cublasSnrm2" cublasSnrm2) :float
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasSnrm2)

(cffi:defcfun ("cublasDnrm2" cublasDnrm2) :double
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDnrm2)

(cffi:defcfun ("cublasScnrm2" cublasScnrm2) :float
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasScnrm2)

(cffi:defcfun ("cublasDznrm2" cublasDznrm2) :double
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDznrm2)

(cffi:defcfun ("cublasSdot" cublasSdot) :float
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSdot)

(cffi:defcfun ("cublasDdot" cublasDdot) :double
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDdot)

(cffi:defcfun ("cublasCdotu" cublasCdotu) :pointer
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCdotu)

(cffi:defcfun ("cublasCdotc" cublasCdotc) :pointer
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCdotc)

(cffi:defcfun ("cublasZdotu" cublasZdotu) :pointer
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZdotu)

(cffi:defcfun ("cublasZdotc" cublasZdotc) :pointer
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZdotc)

(cffi:defcfun ("cublasSscal" cublasSscal) :void
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int))

(cl:export 'cublasSscal)

(cffi:defcfun ("cublasDscal" cublasDscal) :void
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDscal)

(cffi:defcfun ("cublasCscal" cublasCscal) :void
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCscal)

(cffi:defcfun ("cublasZscal" cublasZscal) :void
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZscal)

(cffi:defcfun ("cublasCsscal" cublasCsscal) :void
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCsscal)

(cffi:defcfun ("cublasZdscal" cublasZdscal) :void
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZdscal)

(cffi:defcfun ("cublasSaxpy" cublasSaxpy) :void
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSaxpy)

(cffi:defcfun ("cublasDaxpy" cublasDaxpy) :void
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDaxpy)

(cffi:defcfun ("cublasCaxpy" cublasCaxpy) :void
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCaxpy)

(cffi:defcfun ("cublasZaxpy" cublasZaxpy) :void
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZaxpy)

(cffi:defcfun ("cublasScopy" cublasScopy) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasScopy)

(cffi:defcfun ("cublasDcopy" cublasDcopy) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDcopy)

(cffi:defcfun ("cublasCcopy" cublasCcopy) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCcopy)

(cffi:defcfun ("cublasZcopy" cublasZcopy) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZcopy)

(cffi:defcfun ("cublasSswap" cublasSswap) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSswap)

(cffi:defcfun ("cublasDswap" cublasDswap) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDswap)

(cffi:defcfun ("cublasCswap" cublasCswap) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCswap)

(cffi:defcfun ("cublasZswap" cublasZswap) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZswap)

(cffi:defcfun ("cublasIsamax" cublasIsamax) :int
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasIsamax)

(cffi:defcfun ("cublasIdamax" cublasIdamax) :int
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasIdamax)

(cffi:defcfun ("cublasIcamax" cublasIcamax) :int
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasIcamax)

(cffi:defcfun ("cublasIzamax" cublasIzamax) :int
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasIzamax)

(cffi:defcfun ("cublasIsamin" cublasIsamin) :int
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasIsamin)

(cffi:defcfun ("cublasIdamin" cublasIdamin) :int
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasIdamin)

(cffi:defcfun ("cublasIcamin" cublasIcamin) :int
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasIcamin)

(cffi:defcfun ("cublasIzamin" cublasIzamin) :int
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasIzamin)

(cffi:defcfun ("cublasSasum" cublasSasum) :float
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasSasum)

(cffi:defcfun ("cublasDasum" cublasDasum) :double
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDasum)

(cffi:defcfun ("cublasScasum" cublasScasum) :float
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasScasum)

(cffi:defcfun ("cublasDzasum" cublasDzasum) :double
  (n :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDzasum)

(cffi:defcfun ("cublasSrot" cublasSrot) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (sc :float)
  (ss :float))

(cl:export 'cublasSrot)

(cffi:defcfun ("cublasDrot" cublasDrot) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (sc :double)
  (ss :double))

(cl:export 'cublasDrot)

(cffi:defcfun ("cublasCrot" cublasCrot) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :float)
  (s :pointer))

(cl:export 'cublasCrot)

(cffi:defcfun ("cublasZrot" cublasZrot) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (sc :double)
  (cs :pointer))

(cl:export 'cublasZrot)

(cffi:defcfun ("cublasCsrot" cublasCsrot) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :float)
  (s :float))

(cl:export 'cublasCsrot)

(cffi:defcfun ("cublasZdrot" cublasZdrot) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :double)
  (s :double))

(cl:export 'cublasZdrot)

(cffi:defcfun ("cublasSrotg" cublasSrotg) :void
  (sa :pointer)
  (sb :pointer)
  (sc :pointer)
  (ss :pointer))

(cl:export 'cublasSrotg)

(cffi:defcfun ("cublasDrotg" cublasDrotg) :void
  (sa :pointer)
  (sb :pointer)
  (sc :pointer)
  (ss :pointer))

(cl:export 'cublasDrotg)

(cffi:defcfun ("cublasCrotg" cublasCrotg) :void
  (ca :pointer)
  (cb :pointer)
  (sc :pointer)
  (cs :pointer))

(cl:export 'cublasCrotg)

(cffi:defcfun ("cublasZrotg" cublasZrotg) :void
  (ca :pointer)
  (cb :pointer)
  (sc :pointer)
  (cs :pointer))

(cl:export 'cublasZrotg)

(cffi:defcfun ("cublasSrotm" cublasSrotm) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (sparam :pointer))

(cl:export 'cublasSrotm)

(cffi:defcfun ("cublasDrotm" cublasDrotm) :void
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (sparam :pointer))

(cl:export 'cublasDrotm)

(cffi:defcfun ("cublasSrotmg" cublasSrotmg) :void
  (sd1 :pointer)
  (sd2 :pointer)
  (sx1 :pointer)
  (sy1 :pointer)
  (sparam :pointer))

(cl:export 'cublasSrotmg)

(cffi:defcfun ("cublasDrotmg" cublasDrotmg) :void
  (sd1 :pointer)
  (sd2 :pointer)
  (sx1 :pointer)
  (sy1 :pointer)
  (sparam :pointer))

(cl:export 'cublasDrotmg)

(cffi:defcfun ("cublasSgemv" cublasSgemv) :void
  (trans :char)
  (m :int)
  (n :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :float)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSgemv)

(cffi:defcfun ("cublasDgemv" cublasDgemv) :void
  (trans :char)
  (m :int)
  (n :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :double)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDgemv)

(cffi:defcfun ("cublasCgemv" cublasCgemv) :void
  (trans :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCgemv)

(cffi:defcfun ("cublasZgemv" cublasZgemv) :void
  (trans :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZgemv)

(cffi:defcfun ("cublasSgbmv" cublasSgbmv) :void
  (trans :char)
  (m :int)
  (n :int)
  (kl :int)
  (ku :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :float)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSgbmv)

(cffi:defcfun ("cublasDgbmv" cublasDgbmv) :void
  (trans :char)
  (m :int)
  (n :int)
  (kl :int)
  (ku :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :double)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDgbmv)

(cffi:defcfun ("cublasCgbmv" cublasCgbmv) :void
  (trans :char)
  (m :int)
  (n :int)
  (kl :int)
  (ku :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCgbmv)

(cffi:defcfun ("cublasZgbmv" cublasZgbmv) :void
  (trans :char)
  (m :int)
  (n :int)
  (kl :int)
  (ku :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZgbmv)

(cffi:defcfun ("cublasStrmv" cublasStrmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStrmv)

(cffi:defcfun ("cublasDtrmv" cublasDtrmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtrmv)

(cffi:defcfun ("cublasCtrmv" cublasCtrmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtrmv)

(cffi:defcfun ("cublasZtrmv" cublasZtrmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtrmv)

(cffi:defcfun ("cublasStbmv" cublasStbmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStbmv)

(cffi:defcfun ("cublasDtbmv" cublasDtbmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtbmv)

(cffi:defcfun ("cublasCtbmv" cublasCtbmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtbmv)

(cffi:defcfun ("cublasZtbmv" cublasZtbmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtbmv)

(cffi:defcfun ("cublasStpmv" cublasStpmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStpmv)

(cffi:defcfun ("cublasDtpmv" cublasDtpmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtpmv)

(cffi:defcfun ("cublasCtpmv" cublasCtpmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtpmv)

(cffi:defcfun ("cublasZtpmv" cublasZtpmv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtpmv)

(cffi:defcfun ("cublasStrsv" cublasStrsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStrsv)

(cffi:defcfun ("cublasDtrsv" cublasDtrsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtrsv)

(cffi:defcfun ("cublasCtrsv" cublasCtrsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtrsv)

(cffi:defcfun ("cublasZtrsv" cublasZtrsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtrsv)

(cffi:defcfun ("cublasStpsv" cublasStpsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStpsv)

(cffi:defcfun ("cublasDtpsv" cublasDtpsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtpsv)

(cffi:defcfun ("cublasCtpsv" cublasCtpsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtpsv)

(cffi:defcfun ("cublasZtpsv" cublasZtpsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtpsv)

(cffi:defcfun ("cublasStbsv" cublasStbsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStbsv)

(cffi:defcfun ("cublasDtbsv" cublasDtbsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtbsv)

(cffi:defcfun ("cublasCtbsv" cublasCtbsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtbsv)

(cffi:defcfun ("cublasZtbsv" cublasZtbsv) :void
  (uplo :char)
  (trans :char)
  (diag :char)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtbsv)

(cffi:defcfun ("cublasSsymv" cublasSsymv) :void
  (uplo :char)
  (n :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :float)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSsymv)

(cffi:defcfun ("cublasDsymv" cublasDsymv) :void
  (uplo :char)
  (n :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :double)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDsymv)

(cffi:defcfun ("cublasChemv" cublasChemv) :void
  (uplo :char)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasChemv)

(cffi:defcfun ("cublasZhemv" cublasZhemv) :void
  (uplo :char)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZhemv)

(cffi:defcfun ("cublasSsbmv" cublasSsbmv) :void
  (uplo :char)
  (n :int)
  (k :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :float)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSsbmv)

(cffi:defcfun ("cublasDsbmv" cublasDsbmv) :void
  (uplo :char)
  (n :int)
  (k :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :double)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDsbmv)

(cffi:defcfun ("cublasChbmv" cublasChbmv) :void
  (uplo :char)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasChbmv)

(cffi:defcfun ("cublasZhbmv" cublasZhbmv) :void
  (uplo :char)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZhbmv)

(cffi:defcfun ("cublasSspmv" cublasSspmv) :void
  (uplo :char)
  (n :int)
  (alpha :float)
  (AP :pointer)
  (x :pointer)
  (incx :int)
  (beta :float)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSspmv)

(cffi:defcfun ("cublasDspmv" cublasDspmv) :void
  (uplo :char)
  (n :int)
  (alpha :double)
  (AP :pointer)
  (x :pointer)
  (incx :int)
  (beta :double)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDspmv)

(cffi:defcfun ("cublasChpmv" cublasChpmv) :void
  (uplo :char)
  (n :int)
  (alpha :pointer)
  (AP :pointer)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasChpmv)

(cffi:defcfun ("cublasZhpmv" cublasZhpmv) :void
  (uplo :char)
  (n :int)
  (alpha :pointer)
  (AP :pointer)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZhpmv)

(cffi:defcfun ("cublasSger" cublasSger) :void
  (m :int)
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasSger)

(cffi:defcfun ("cublasDger" cublasDger) :void
  (m :int)
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasDger)

(cffi:defcfun ("cublasCgeru" cublasCgeru) :void
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCgeru)

(cffi:defcfun ("cublasCgerc" cublasCgerc) :void
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCgerc)

(cffi:defcfun ("cublasZgeru" cublasZgeru) :void
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZgeru)

(cffi:defcfun ("cublasZgerc" cublasZgerc) :void
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZgerc)

(cffi:defcfun ("cublasSsyr" cublasSsyr) :void
  (uplo :char)
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasSsyr)

(cffi:defcfun ("cublasDsyr" cublasDsyr) :void
  (uplo :char)
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasDsyr)

(cffi:defcfun ("cublasCher" cublasCher) :void
  (uplo :char)
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCher)

(cffi:defcfun ("cublasZher" cublasZher) :void
  (uplo :char)
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZher)

(cffi:defcfun ("cublasSspr" cublasSspr) :void
  (uplo :char)
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int)
  (AP :pointer))

(cl:export 'cublasSspr)

(cffi:defcfun ("cublasDspr" cublasDspr) :void
  (uplo :char)
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int)
  (AP :pointer))

(cl:export 'cublasDspr)

(cffi:defcfun ("cublasChpr" cublasChpr) :void
  (uplo :char)
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int)
  (AP :pointer))

(cl:export 'cublasChpr)

(cffi:defcfun ("cublasZhpr" cublasZhpr) :void
  (uplo :char)
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int)
  (AP :pointer))

(cl:export 'cublasZhpr)

(cffi:defcfun ("cublasSsyr2" cublasSsyr2) :void
  (uplo :char)
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasSsyr2)

(cffi:defcfun ("cublasDsyr2" cublasDsyr2) :void
  (uplo :char)
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasDsyr2)

(cffi:defcfun ("cublasCher2" cublasCher2) :void
  (uplo :char)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCher2)

(cffi:defcfun ("cublasZher2" cublasZher2) :void
  (uplo :char)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZher2)

(cffi:defcfun ("cublasSspr2" cublasSspr2) :void
  (uplo :char)
  (n :int)
  (alpha :float)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (AP :pointer))

(cl:export 'cublasSspr2)

(cffi:defcfun ("cublasDspr2" cublasDspr2) :void
  (uplo :char)
  (n :int)
  (alpha :double)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (AP :pointer))

(cl:export 'cublasDspr2)

(cffi:defcfun ("cublasChpr2" cublasChpr2) :void
  (uplo :char)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (AP :pointer))

(cl:export 'cublasChpr2)

(cffi:defcfun ("cublasZhpr2" cublasZhpr2) :void
  (uplo :char)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (AP :pointer))

(cl:export 'cublasZhpr2)

(cffi:defcfun ("cublasSgemm" cublasSgemm) :void
  (transa :char)
  (transb :char)
  (m :int)
  (n :int)
  (k :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :float)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSgemm)

(cffi:defcfun ("cublasDgemm" cublasDgemm) :void
  (transa :char)
  (transb :char)
  (m :int)
  (n :int)
  (k :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :double)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDgemm)

(cffi:defcfun ("cublasCgemm" cublasCgemm) :void
  (transa :char)
  (transb :char)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCgemm)

(cffi:defcfun ("cublasZgemm" cublasZgemm) :void
  (transa :char)
  (transb :char)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZgemm)

(cffi:defcfun ("cublasSsyrk" cublasSsyrk) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (beta :float)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSsyrk)

(cffi:defcfun ("cublasDsyrk" cublasDsyrk) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (beta :double)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDsyrk)

(cffi:defcfun ("cublasCsyrk" cublasCsyrk) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCsyrk)

(cffi:defcfun ("cublasZsyrk" cublasZsyrk) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZsyrk)

(cffi:defcfun ("cublasCherk" cublasCherk) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (beta :float)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCherk)

(cffi:defcfun ("cublasZherk" cublasZherk) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (beta :double)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZherk)

(cffi:defcfun ("cublasSsyr2k" cublasSsyr2k) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :float)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSsyr2k)

(cffi:defcfun ("cublasDsyr2k" cublasDsyr2k) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :double)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDsyr2k)

(cffi:defcfun ("cublasCsyr2k" cublasCsyr2k) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCsyr2k)

(cffi:defcfun ("cublasZsyr2k" cublasZsyr2k) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZsyr2k)

(cffi:defcfun ("cublasCher2k" cublasCher2k) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :float)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCher2k)

(cffi:defcfun ("cublasZher2k" cublasZher2k) :void
  (uplo :char)
  (trans :char)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :double)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZher2k)

(cffi:defcfun ("cublasSsymm" cublasSsymm) :void
  (side :char)
  (uplo :char)
  (m :int)
  (n :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :float)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSsymm)

(cffi:defcfun ("cublasDsymm" cublasDsymm) :void
  (side :char)
  (uplo :char)
  (m :int)
  (n :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :double)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDsymm)

(cffi:defcfun ("cublasCsymm" cublasCsymm) :void
  (side :char)
  (uplo :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCsymm)

(cffi:defcfun ("cublasZsymm" cublasZsymm) :void
  (side :char)
  (uplo :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZsymm)

(cffi:defcfun ("cublasChemm" cublasChemm) :void
  (side :char)
  (uplo :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasChemm)

(cffi:defcfun ("cublasZhemm" cublasZhemm) :void
  (side :char)
  (uplo :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZhemm)

(cffi:defcfun ("cublasStrsm" cublasStrsm) :void
  (side :char)
  (uplo :char)
  (transa :char)
  (diag :char)
  (m :int)
  (n :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasStrsm)

(cffi:defcfun ("cublasDtrsm" cublasDtrsm) :void
  (side :char)
  (uplo :char)
  (transa :char)
  (diag :char)
  (m :int)
  (n :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasDtrsm)

(cffi:defcfun ("cublasCtrsm" cublasCtrsm) :void
  (side :char)
  (uplo :char)
  (transa :char)
  (diag :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasCtrsm)

(cffi:defcfun ("cublasZtrsm" cublasZtrsm) :void
  (side :char)
  (uplo :char)
  (transa :char)
  (diag :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasZtrsm)

(cffi:defcfun ("cublasStrmm" cublasStrmm) :void
  (side :char)
  (uplo :char)
  (transa :char)
  (diag :char)
  (m :int)
  (n :int)
  (alpha :float)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasStrmm)

(cffi:defcfun ("cublasDtrmm" cublasDtrmm) :void
  (side :char)
  (uplo :char)
  (transa :char)
  (diag :char)
  (m :int)
  (n :int)
  (alpha :double)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasDtrmm)

(cffi:defcfun ("cublasCtrmm" cublasCtrmm) :void
  (side :char)
  (uplo :char)
  (transa :char)
  (diag :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasCtrmm)

(cffi:defcfun ("cublasZtrmm" cublasZtrmm) :void
  (side :char)
  (uplo :char)
  (transa :char)
  (diag :char)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasZtrmm)

(cffi:defcenum cublasStatus_t
	(:CUBLAS_STATUS_SUCCESS #.0)
	(:CUBLAS_STATUS_NOT_INITIALIZED #.1)
	(:CUBLAS_STATUS_ALLOC_FAILED #.3)
	(:CUBLAS_STATUS_INVALID_VALUE #.7)
	(:CUBLAS_STATUS_ARCH_MISMATCH #.8)
	(:CUBLAS_STATUS_MAPPING_ERROR #.11)
	(:CUBLAS_STATUS_EXECUTION_FAILED #.13)
	(:CUBLAS_STATUS_INTERNAL_ERROR #.14)
	(:CUBLAS_STATUS_NOT_SUPPORTED #.15)
	(:CUBLAS_STATUS_LICENSE_ERROR #.16))

(cl:export 'cublasStatus_t)

(cffi:defcenum cublasFillMode_t
	(:CUBLAS_FILL_MODE_LOWER #.0)
	(:CUBLAS_FILL_MODE_UPPER #.1))

(cl:export 'cublasFillMode_t)

(cffi:defcenum cublasDiagType_t
	(:CUBLAS_DIAG_NON_UNIT #.0)
	(:CUBLAS_DIAG_UNIT #.1))

(cl:export 'cublasDiagType_t)

(cffi:defcenum cublasSideMode_t
	(:CUBLAS_SIDE_LEFT #.0)
	(:CUBLAS_SIDE_RIGHT #.1))

(cl:export 'cublasSideMode_t)

(cffi:defcenum cublasOperation_t
	(:CUBLAS_OP_N #.0)
	(:CUBLAS_OP_T #.1)
	(:CUBLAS_OP_C #.2))

(cl:export 'cublasOperation_t)

(cffi:defcenum cublasPointerMode_t
	(:CUBLAS_POINTER_MODE_HOST #.0)
	(:CUBLAS_POINTER_MODE_DEVICE #.1))

(cl:export 'cublasPointerMode_t)

(cffi:defcenum cublasAtomicsMode_t
	(:CUBLAS_ATOMICS_NOT_ALLOWED #.0)
	(:CUBLAS_ATOMICS_ALLOWED #.1))

(cl:export 'cublasAtomicsMode_t)

(cffi:defcenum cublasGemmAlgo_t
	(:CUBLAS_GEMM_DFALT #.-1)
	(:CUBLAS_GEMM_DEFAULT #.-1)
	(:CUBLAS_GEMM_ALGO0 #.0)
	(:CUBLAS_GEMM_ALGO1 #.1)
	(:CUBLAS_GEMM_ALGO2 #.2)
	(:CUBLAS_GEMM_ALGO3 #.3)
	(:CUBLAS_GEMM_ALGO4 #.4)
	(:CUBLAS_GEMM_ALGO5 #.5)
	(:CUBLAS_GEMM_ALGO6 #.6)
	(:CUBLAS_GEMM_ALGO7 #.7)
	(:CUBLAS_GEMM_ALGO8 #.8)
	(:CUBLAS_GEMM_ALGO9 #.9)
	(:CUBLAS_GEMM_ALGO10 #.10)
	(:CUBLAS_GEMM_ALGO11 #.11)
	(:CUBLAS_GEMM_ALGO12 #.12)
	(:CUBLAS_GEMM_ALGO13 #.13)
	(:CUBLAS_GEMM_ALGO14 #.14)
	(:CUBLAS_GEMM_ALGO15 #.15)
	(:CUBLAS_GEMM_ALGO16 #.16)
	(:CUBLAS_GEMM_ALGO17 #.17)
	(:CUBLAS_GEMM_DEFAULT_TENSOR_OP #.99)
	(:CUBLAS_GEMM_DFALT_TENSOR_OP #.99)
	(:CUBLAS_GEMM_ALGO0_TENSOR_OP #.100)
	(:CUBLAS_GEMM_ALGO1_TENSOR_OP #.101)
	(:CUBLAS_GEMM_ALGO2_TENSOR_OP #.102)
	(:CUBLAS_GEMM_ALGO3_TENSOR_OP #.103)
	(:CUBLAS_GEMM_ALGO4_TENSOR_OP #.104))

(cl:export 'cublasGemmAlgo_t)

(cffi:defcenum cublasMath_t
	(:CUBLAS_DEFAULT_MATH #.0)
	(:CUBLAS_TENSOR_OP_MATH #.1))

(cl:export 'cublasMath_t)

(cffi:defcfun ("cublasCreate_v2" cublasCreate_v2) cublasStatus_t
  (handle :pointer))

(cl:export 'cublasCreate_v2)

(cffi:defcfun ("cublasDestroy_v2" cublasDestroy_v2) cublasStatus_t
  (handle :pointer))

(cl:export 'cublasDestroy_v2)

(cffi:defcfun ("cublasGetVersion_v2" cublasGetVersion_v2) cublasStatus_t
  (handle :pointer)
  (version :pointer))

(cl:export 'cublasGetVersion_v2)

(cffi:defcfun ("cublasGetProperty" cublasGetProperty) cublasStatus_t
  (type :pointer)
  (value :pointer))

(cl:export 'cublasGetProperty)

(cffi:defcfun ("cublasSetStream_v2" cublasSetStream_v2) cublasStatus_t
  (handle :pointer)
  (streamId :pointer))

(cl:export 'cublasSetStream_v2)

(cffi:defcfun ("cublasGetStream_v2" cublasGetStream_v2) cublasStatus_t
  (handle :pointer)
  (streamId :pointer))

(cl:export 'cublasGetStream_v2)

(cffi:defcfun ("cublasGetPointerMode_v2" cublasGetPointerMode_v2) cublasStatus_t
  (handle :pointer)
  (mode :pointer))

(cl:export 'cublasGetPointerMode_v2)

(cffi:defcfun ("cublasSetPointerMode_v2" cublasSetPointerMode_v2) cublasStatus_t
  (handle :pointer)
  (mode cublasPointerMode_t))

(cl:export 'cublasSetPointerMode_v2)

(cffi:defcfun ("cublasGetAtomicsMode" cublasGetAtomicsMode) cublasStatus_t
  (handle :pointer)
  (mode :pointer))

(cl:export 'cublasGetAtomicsMode)

(cffi:defcfun ("cublasSetAtomicsMode" cublasSetAtomicsMode) cublasStatus_t
  (handle :pointer)
  (mode cublasAtomicsMode_t))

(cl:export 'cublasSetAtomicsMode)

(cffi:defcfun ("cublasGetMathMode" cublasGetMathMode) cublasStatus_t
  (handle :pointer)
  (mode :pointer))

(cl:export 'cublasGetMathMode)

(cffi:defcfun ("cublasSetMathMode" cublasSetMathMode) cublasStatus_t
  (handle :pointer)
  (mode cublasMath_t))

(cl:export 'cublasSetMathMode)

(cffi:defcfun ("cublasSetVector" cublasSetVector) cublasStatus_t
  (n :int)
  (elemSize :int)
  (x :pointer)
  (incx :int)
  (devicePtr :pointer)
  (incy :int))

(cl:export 'cublasSetVector)

(cffi:defcfun ("cublasGetVector" cublasGetVector) cublasStatus_t
  (n :int)
  (elemSize :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasGetVector)

(cffi:defcfun ("cublasSetMatrix" cublasSetMatrix) cublasStatus_t
  (rows :int)
  (cols :int)
  (elemSize :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasSetMatrix)

(cffi:defcfun ("cublasGetMatrix" cublasGetMatrix) cublasStatus_t
  (rows :int)
  (cols :int)
  (elemSize :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasGetMatrix)

(cffi:defcfun ("cublasSetVectorAsync" cublasSetVectorAsync) cublasStatus_t
  (n :int)
  (elemSize :int)
  (hostPtr :pointer)
  (incx :int)
  (devicePtr :pointer)
  (incy :int)
  (stream :pointer))

(cl:export 'cublasSetVectorAsync)

(cffi:defcfun ("cublasGetVectorAsync" cublasGetVectorAsync) cublasStatus_t
  (n :int)
  (elemSize :int)
  (devicePtr :pointer)
  (incx :int)
  (hostPtr :pointer)
  (incy :int)
  (stream :pointer))

(cl:export 'cublasGetVectorAsync)

(cffi:defcfun ("cublasSetMatrixAsync" cublasSetMatrixAsync) cublasStatus_t
  (rows :int)
  (cols :int)
  (elemSize :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (stream :pointer))

(cl:export 'cublasSetMatrixAsync)

(cffi:defcfun ("cublasGetMatrixAsync" cublasGetMatrixAsync) cublasStatus_t
  (rows :int)
  (cols :int)
  (elemSize :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (stream :pointer))

(cl:export 'cublasGetMatrixAsync)

(cffi:defcfun ("cublasXerbla" cublasXerbla) :void
  (srName :string)
  (info :int))

(cl:export 'cublasXerbla)

(cffi:defcfun ("cublasNrm2Ex" cublasNrm2Ex) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (xType :pointer)
  (incx :int)
  (result :pointer)
  (resultType :pointer)
  (executionType :pointer))

(cl:export 'cublasNrm2Ex)

(cffi:defcfun ("cublasSnrm2_v2" cublasSnrm2_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasSnrm2_v2)

(cffi:defcfun ("cublasDnrm2_v2" cublasDnrm2_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasDnrm2_v2)

(cffi:defcfun ("cublasScnrm2_v2" cublasScnrm2_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasScnrm2_v2)

(cffi:defcfun ("cublasDznrm2_v2" cublasDznrm2_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasDznrm2_v2)

(cffi:defcfun ("cublasDotEx" cublasDotEx) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (xType :pointer)
  (incx :int)
  (y :pointer)
  (yType :pointer)
  (incy :int)
  (result :pointer)
  (resultType :pointer)
  (executionType :pointer))

(cl:export 'cublasDotEx)

(cffi:defcfun ("cublasDotcEx" cublasDotcEx) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (xType :pointer)
  (incx :int)
  (y :pointer)
  (yType :pointer)
  (incy :int)
  (result :pointer)
  (resultType :pointer)
  (executionType :pointer))

(cl:export 'cublasDotcEx)

(cffi:defcfun ("cublasSdot_v2" cublasSdot_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (result :pointer))

(cl:export 'cublasSdot_v2)

(cffi:defcfun ("cublasDdot_v2" cublasDdot_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (result :pointer))

(cl:export 'cublasDdot_v2)

(cffi:defcfun ("cublasCdotu_v2" cublasCdotu_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (result :pointer))

(cl:export 'cublasCdotu_v2)

(cffi:defcfun ("cublasCdotc_v2" cublasCdotc_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (result :pointer))

(cl:export 'cublasCdotc_v2)

(cffi:defcfun ("cublasZdotu_v2" cublasZdotu_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (result :pointer))

(cl:export 'cublasZdotu_v2)

(cffi:defcfun ("cublasZdotc_v2" cublasZdotc_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (result :pointer))

(cl:export 'cublasZdotc_v2)

(cffi:defcfun ("cublasScalEx" cublasScalEx) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (alphaType :pointer)
  (x :pointer)
  (xType :pointer)
  (incx :int)
  (executionType :pointer))

(cl:export 'cublasScalEx)

(cffi:defcfun ("cublasSscal_v2" cublasSscal_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasSscal_v2)

(cffi:defcfun ("cublasDscal_v2" cublasDscal_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDscal_v2)

(cffi:defcfun ("cublasCscal_v2" cublasCscal_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCscal_v2)

(cffi:defcfun ("cublasCsscal_v2" cublasCsscal_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCsscal_v2)

(cffi:defcfun ("cublasZscal_v2" cublasZscal_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZscal_v2)

(cffi:defcfun ("cublasZdscal_v2" cublasZdscal_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZdscal_v2)

(cffi:defcfun ("cublasAxpyEx" cublasAxpyEx) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (alphaType :pointer)
  (x :pointer)
  (xType :pointer)
  (incx :int)
  (y :pointer)
  (yType :pointer)
  (incy :int)
  (executiontype :pointer))

(cl:export 'cublasAxpyEx)

(cffi:defcfun ("cublasSaxpy_v2" cublasSaxpy_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSaxpy_v2)

(cffi:defcfun ("cublasDaxpy_v2" cublasDaxpy_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDaxpy_v2)

(cffi:defcfun ("cublasCaxpy_v2" cublasCaxpy_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCaxpy_v2)

(cffi:defcfun ("cublasZaxpy_v2" cublasZaxpy_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZaxpy_v2)

(cffi:defcfun ("cublasScopy_v2" cublasScopy_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasScopy_v2)

(cffi:defcfun ("cublasDcopy_v2" cublasDcopy_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDcopy_v2)

(cffi:defcfun ("cublasCcopy_v2" cublasCcopy_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCcopy_v2)

(cffi:defcfun ("cublasZcopy_v2" cublasZcopy_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZcopy_v2)

(cffi:defcfun ("cublasSswap_v2" cublasSswap_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSswap_v2)

(cffi:defcfun ("cublasDswap_v2" cublasDswap_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDswap_v2)

(cffi:defcfun ("cublasCswap_v2" cublasCswap_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCswap_v2)

(cffi:defcfun ("cublasZswap_v2" cublasZswap_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZswap_v2)

(cffi:defcfun ("cublasIsamax_v2" cublasIsamax_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasIsamax_v2)

(cffi:defcfun ("cublasIdamax_v2" cublasIdamax_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasIdamax_v2)

(cffi:defcfun ("cublasIcamax_v2" cublasIcamax_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasIcamax_v2)

(cffi:defcfun ("cublasIzamax_v2" cublasIzamax_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasIzamax_v2)

(cffi:defcfun ("cublasIsamin_v2" cublasIsamin_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasIsamin_v2)

(cffi:defcfun ("cublasIdamin_v2" cublasIdamin_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasIdamin_v2)

(cffi:defcfun ("cublasIcamin_v2" cublasIcamin_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasIcamin_v2)

(cffi:defcfun ("cublasIzamin_v2" cublasIzamin_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasIzamin_v2)

(cffi:defcfun ("cublasSasum_v2" cublasSasum_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasSasum_v2)

(cffi:defcfun ("cublasDasum_v2" cublasDasum_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasDasum_v2)

(cffi:defcfun ("cublasScasum_v2" cublasScasum_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasScasum_v2)

(cffi:defcfun ("cublasDzasum_v2" cublasDzasum_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (result :pointer))

(cl:export 'cublasDzasum_v2)

(cffi:defcfun ("cublasSrot_v2" cublasSrot_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasSrot_v2)

(cffi:defcfun ("cublasDrot_v2" cublasDrot_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasDrot_v2)

(cffi:defcfun ("cublasCrot_v2" cublasCrot_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasCrot_v2)

(cffi:defcfun ("cublasCsrot_v2" cublasCsrot_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasCsrot_v2)

(cffi:defcfun ("cublasZrot_v2" cublasZrot_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasZrot_v2)

(cffi:defcfun ("cublasZdrot_v2" cublasZdrot_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasZdrot_v2)

(cffi:defcfun ("cublasSrotg_v2" cublasSrotg_v2) cublasStatus_t
  (handle :pointer)
  (a :pointer)
  (b :pointer)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasSrotg_v2)

(cffi:defcfun ("cublasDrotg_v2" cublasDrotg_v2) cublasStatus_t
  (handle :pointer)
  (a :pointer)
  (b :pointer)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasDrotg_v2)

(cffi:defcfun ("cublasCrotg_v2" cublasCrotg_v2) cublasStatus_t
  (handle :pointer)
  (a :pointer)
  (b :pointer)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasCrotg_v2)

(cffi:defcfun ("cublasZrotg_v2" cublasZrotg_v2) cublasStatus_t
  (handle :pointer)
  (a :pointer)
  (b :pointer)
  (c :pointer)
  (s :pointer))

(cl:export 'cublasZrotg_v2)

(cffi:defcfun ("cublasSrotm_v2" cublasSrotm_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (param :pointer))

(cl:export 'cublasSrotm_v2)

(cffi:defcfun ("cublasDrotm_v2" cublasDrotm_v2) cublasStatus_t
  (handle :pointer)
  (n :int)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (param :pointer))

(cl:export 'cublasDrotm_v2)

(cffi:defcfun ("cublasSrotmg_v2" cublasSrotmg_v2) cublasStatus_t
  (handle :pointer)
  (d1 :pointer)
  (d2 :pointer)
  (x1 :pointer)
  (y1 :pointer)
  (param :pointer))

(cl:export 'cublasSrotmg_v2)

(cffi:defcfun ("cublasDrotmg_v2" cublasDrotmg_v2) cublasStatus_t
  (handle :pointer)
  (d1 :pointer)
  (d2 :pointer)
  (x1 :pointer)
  (y1 :pointer)
  (param :pointer))

(cl:export 'cublasDrotmg_v2)

(cffi:defcfun ("cublasSgemv_v2" cublasSgemv_v2) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSgemv_v2)

(cffi:defcfun ("cublasDgemv_v2" cublasDgemv_v2) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDgemv_v2)

(cffi:defcfun ("cublasCgemv_v2" cublasCgemv_v2) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCgemv_v2)

(cffi:defcfun ("cublasZgemv_v2" cublasZgemv_v2) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZgemv_v2)

(cffi:defcfun ("cublasSgbmv_v2" cublasSgbmv_v2) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (kl :int)
  (ku :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSgbmv_v2)

(cffi:defcfun ("cublasDgbmv_v2" cublasDgbmv_v2) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (kl :int)
  (ku :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDgbmv_v2)

(cffi:defcfun ("cublasCgbmv_v2" cublasCgbmv_v2) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (kl :int)
  (ku :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCgbmv_v2)

(cffi:defcfun ("cublasZgbmv_v2" cublasZgbmv_v2) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (kl :int)
  (ku :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZgbmv_v2)

(cffi:defcfun ("cublasStrmv_v2" cublasStrmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStrmv_v2)

(cffi:defcfun ("cublasDtrmv_v2" cublasDtrmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtrmv_v2)

(cffi:defcfun ("cublasCtrmv_v2" cublasCtrmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtrmv_v2)

(cffi:defcfun ("cublasZtrmv_v2" cublasZtrmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtrmv_v2)

(cffi:defcfun ("cublasStbmv_v2" cublasStbmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStbmv_v2)

(cffi:defcfun ("cublasDtbmv_v2" cublasDtbmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtbmv_v2)

(cffi:defcfun ("cublasCtbmv_v2" cublasCtbmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtbmv_v2)

(cffi:defcfun ("cublasZtbmv_v2" cublasZtbmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtbmv_v2)

(cffi:defcfun ("cublasStpmv_v2" cublasStpmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStpmv_v2)

(cffi:defcfun ("cublasDtpmv_v2" cublasDtpmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtpmv_v2)

(cffi:defcfun ("cublasCtpmv_v2" cublasCtpmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtpmv_v2)

(cffi:defcfun ("cublasZtpmv_v2" cublasZtpmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtpmv_v2)

(cffi:defcfun ("cublasStrsv_v2" cublasStrsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStrsv_v2)

(cffi:defcfun ("cublasDtrsv_v2" cublasDtrsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtrsv_v2)

(cffi:defcfun ("cublasCtrsv_v2" cublasCtrsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtrsv_v2)

(cffi:defcfun ("cublasZtrsv_v2" cublasZtrsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtrsv_v2)

(cffi:defcfun ("cublasStpsv_v2" cublasStpsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStpsv_v2)

(cffi:defcfun ("cublasDtpsv_v2" cublasDtpsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtpsv_v2)

(cffi:defcfun ("cublasCtpsv_v2" cublasCtpsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtpsv_v2)

(cffi:defcfun ("cublasZtpsv_v2" cublasZtpsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (AP :pointer)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtpsv_v2)

(cffi:defcfun ("cublasStbsv_v2" cublasStbsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasStbsv_v2)

(cffi:defcfun ("cublasDtbsv_v2" cublasDtbsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasDtbsv_v2)

(cffi:defcfun ("cublasCtbsv_v2" cublasCtbsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasCtbsv_v2)

(cffi:defcfun ("cublasZtbsv_v2" cublasZtbsv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int))

(cl:export 'cublasZtbsv_v2)

(cffi:defcfun ("cublasSsymv_v2" cublasSsymv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSsymv_v2)

(cffi:defcfun ("cublasDsymv_v2" cublasDsymv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDsymv_v2)

(cffi:defcfun ("cublasCsymv_v2" cublasCsymv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasCsymv_v2)

(cffi:defcfun ("cublasZsymv_v2" cublasZsymv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZsymv_v2)

(cffi:defcfun ("cublasChemv_v2" cublasChemv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasChemv_v2)

(cffi:defcfun ("cublasZhemv_v2" cublasZhemv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZhemv_v2)

(cffi:defcfun ("cublasSsbmv_v2" cublasSsbmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSsbmv_v2)

(cffi:defcfun ("cublasDsbmv_v2" cublasDsbmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDsbmv_v2)

(cffi:defcfun ("cublasChbmv_v2" cublasChbmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasChbmv_v2)

(cffi:defcfun ("cublasZhbmv_v2" cublasZhbmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZhbmv_v2)

(cffi:defcfun ("cublasSspmv_v2" cublasSspmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (AP :pointer)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasSspmv_v2)

(cffi:defcfun ("cublasDspmv_v2" cublasDspmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (AP :pointer)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasDspmv_v2)

(cffi:defcfun ("cublasChpmv_v2" cublasChpmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (AP :pointer)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasChpmv_v2)

(cffi:defcfun ("cublasZhpmv_v2" cublasZhpmv_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (AP :pointer)
  (x :pointer)
  (incx :int)
  (beta :pointer)
  (y :pointer)
  (incy :int))

(cl:export 'cublasZhpmv_v2)

(cffi:defcfun ("cublasSger_v2" cublasSger_v2) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasSger_v2)

(cffi:defcfun ("cublasDger_v2" cublasDger_v2) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasDger_v2)

(cffi:defcfun ("cublasCgeru_v2" cublasCgeru_v2) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCgeru_v2)

(cffi:defcfun ("cublasCgerc_v2" cublasCgerc_v2) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCgerc_v2)

(cffi:defcfun ("cublasZgeru_v2" cublasZgeru_v2) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZgeru_v2)

(cffi:defcfun ("cublasZgerc_v2" cublasZgerc_v2) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZgerc_v2)

(cffi:defcfun ("cublasSsyr_v2" cublasSsyr_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasSsyr_v2)

(cffi:defcfun ("cublasDsyr_v2" cublasDsyr_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasDsyr_v2)

(cffi:defcfun ("cublasCsyr_v2" cublasCsyr_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCsyr_v2)

(cffi:defcfun ("cublasZsyr_v2" cublasZsyr_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZsyr_v2)

(cffi:defcfun ("cublasCher_v2" cublasCher_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCher_v2)

(cffi:defcfun ("cublasZher_v2" cublasZher_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZher_v2)

(cffi:defcfun ("cublasSspr_v2" cublasSspr_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (AP :pointer))

(cl:export 'cublasSspr_v2)

(cffi:defcfun ("cublasDspr_v2" cublasDspr_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (AP :pointer))

(cl:export 'cublasDspr_v2)

(cffi:defcfun ("cublasChpr_v2" cublasChpr_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (AP :pointer))

(cl:export 'cublasChpr_v2)

(cffi:defcfun ("cublasZhpr_v2" cublasZhpr_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (AP :pointer))

(cl:export 'cublasZhpr_v2)

(cffi:defcfun ("cublasSsyr2_v2" cublasSsyr2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasSsyr2_v2)

(cffi:defcfun ("cublasDsyr2_v2" cublasDsyr2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasDsyr2_v2)

(cffi:defcfun ("cublasCsyr2_v2" cublasCsyr2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCsyr2_v2)

(cffi:defcfun ("cublasZsyr2_v2" cublasZsyr2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZsyr2_v2)

(cffi:defcfun ("cublasCher2_v2" cublasCher2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCher2_v2)

(cffi:defcfun ("cublasZher2_v2" cublasZher2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZher2_v2)

(cffi:defcfun ("cublasSspr2_v2" cublasSspr2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (AP :pointer))

(cl:export 'cublasSspr2_v2)

(cffi:defcfun ("cublasDspr2_v2" cublasDspr2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (AP :pointer))

(cl:export 'cublasDspr2_v2)

(cffi:defcfun ("cublasChpr2_v2" cublasChpr2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (AP :pointer))

(cl:export 'cublasChpr2_v2)

(cffi:defcfun ("cublasZhpr2_v2" cublasZhpr2_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (alpha :pointer)
  (x :pointer)
  (incx :int)
  (y :pointer)
  (incy :int)
  (AP :pointer))

(cl:export 'cublasZhpr2_v2)

(cffi:defcfun ("cublasSgemm_v2" cublasSgemm_v2) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSgemm_v2)

(cffi:defcfun ("cublasDgemm_v2" cublasDgemm_v2) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDgemm_v2)

(cffi:defcfun ("cublasCgemm_v2" cublasCgemm_v2) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCgemm_v2)

(cffi:defcfun ("cublasCgemm3m" cublasCgemm3m) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCgemm3m)

(cffi:defcfun ("cublasCgemm3mEx" cublasCgemm3mEx) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (B :pointer)
  (Btype :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int))

(cl:export 'cublasCgemm3mEx)

(cffi:defcfun ("cublasZgemm_v2" cublasZgemm_v2) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZgemm_v2)

(cffi:defcfun ("cublasZgemm3m" cublasZgemm3m) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZgemm3m)

(cffi:defcfun ("cublasSgemmEx" cublasSgemmEx) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (B :pointer)
  (Btype :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int))

(cl:export 'cublasSgemmEx)

(cffi:defcfun ("cublasGemmEx" cublasGemmEx) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (B :pointer)
  (Btype :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int)
  (computeType :pointer)
  (algo cublasGemmAlgo_t))

(cl:export 'cublasGemmEx)

(cffi:defcfun ("cublasCgemmEx" cublasCgemmEx) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (B :pointer)
  (Btype :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int))

(cl:export 'cublasCgemmEx)

(cffi:defcfun ("cublasUint8gemmBias" cublasUint8gemmBias) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (transc cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (A_bias :int)
  (lda :int)
  (B :pointer)
  (B_bias :int)
  (ldb :int)
  (C :pointer)
  (C_bias :int)
  (ldc :int)
  (C_mult :int)
  (C_shift :int))

(cl:export 'cublasUint8gemmBias)

(cffi:defcfun ("cublasSsyrk_v2" cublasSsyrk_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSsyrk_v2)

(cffi:defcfun ("cublasDsyrk_v2" cublasDsyrk_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDsyrk_v2)

(cffi:defcfun ("cublasCsyrk_v2" cublasCsyrk_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCsyrk_v2)

(cffi:defcfun ("cublasZsyrk_v2" cublasZsyrk_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZsyrk_v2)

(cffi:defcfun ("cublasCsyrkEx" cublasCsyrkEx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int))

(cl:export 'cublasCsyrkEx)

(cffi:defcfun ("cublasCsyrk3mEx" cublasCsyrk3mEx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int))

(cl:export 'cublasCsyrk3mEx)

(cffi:defcfun ("cublasCherk_v2" cublasCherk_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCherk_v2)

(cffi:defcfun ("cublasZherk_v2" cublasZherk_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZherk_v2)

(cffi:defcfun ("cublasCherkEx" cublasCherkEx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int))

(cl:export 'cublasCherkEx)

(cffi:defcfun ("cublasCherk3mEx" cublasCherk3mEx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int))

(cl:export 'cublasCherk3mEx)

(cffi:defcfun ("cublasSsyr2k_v2" cublasSsyr2k_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSsyr2k_v2)

(cffi:defcfun ("cublasDsyr2k_v2" cublasDsyr2k_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDsyr2k_v2)

(cffi:defcfun ("cublasCsyr2k_v2" cublasCsyr2k_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCsyr2k_v2)

(cffi:defcfun ("cublasZsyr2k_v2" cublasZsyr2k_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZsyr2k_v2)

(cffi:defcfun ("cublasCher2k_v2" cublasCher2k_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCher2k_v2)

(cffi:defcfun ("cublasZher2k_v2" cublasZher2k_v2) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZher2k_v2)

(cffi:defcfun ("cublasSsyrkx" cublasSsyrkx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSsyrkx)

(cffi:defcfun ("cublasDsyrkx" cublasDsyrkx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDsyrkx)

(cffi:defcfun ("cublasCsyrkx" cublasCsyrkx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCsyrkx)

(cffi:defcfun ("cublasZsyrkx" cublasZsyrkx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZsyrkx)

(cffi:defcfun ("cublasCherkx" cublasCherkx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCherkx)

(cffi:defcfun ("cublasZherkx" cublasZherkx) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZherkx)

(cffi:defcfun ("cublasSsymm_v2" cublasSsymm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSsymm_v2)

(cffi:defcfun ("cublasDsymm_v2" cublasDsymm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDsymm_v2)

(cffi:defcfun ("cublasCsymm_v2" cublasCsymm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCsymm_v2)

(cffi:defcfun ("cublasZsymm_v2" cublasZsymm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZsymm_v2)

(cffi:defcfun ("cublasChemm_v2" cublasChemm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasChemm_v2)

(cffi:defcfun ("cublasZhemm_v2" cublasZhemm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (beta :pointer)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZhemm_v2)

(cffi:defcfun ("cublasStrsm_v2" cublasStrsm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasStrsm_v2)

(cffi:defcfun ("cublasDtrsm_v2" cublasDtrsm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasDtrsm_v2)

(cffi:defcfun ("cublasCtrsm_v2" cublasCtrsm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasCtrsm_v2)

(cffi:defcfun ("cublasZtrsm_v2" cublasZtrsm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int))

(cl:export 'cublasZtrsm_v2)

(cffi:defcfun ("cublasStrmm_v2" cublasStrmm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasStrmm_v2)

(cffi:defcfun ("cublasDtrmm_v2" cublasDtrmm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDtrmm_v2)

(cffi:defcfun ("cublasCtrmm_v2" cublasCtrmm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCtrmm_v2)

(cffi:defcfun ("cublasZtrmm_v2" cublasZtrmm_v2) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZtrmm_v2)

(cffi:defcfun ("cublasSgemmBatched" cublasSgemmBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (Aarray :pointer)
  (lda :int)
  (Barray :pointer)
  (ldb :int)
  (beta :pointer)
  (Carray :pointer)
  (ldc :int)
  (batchCount :int))

(cl:export 'cublasSgemmBatched)

(cffi:defcfun ("cublasDgemmBatched" cublasDgemmBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (Aarray :pointer)
  (lda :int)
  (Barray :pointer)
  (ldb :int)
  (beta :pointer)
  (Carray :pointer)
  (ldc :int)
  (batchCount :int))

(cl:export 'cublasDgemmBatched)

(cffi:defcfun ("cublasCgemmBatched" cublasCgemmBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (Aarray :pointer)
  (lda :int)
  (Barray :pointer)
  (ldb :int)
  (beta :pointer)
  (Carray :pointer)
  (ldc :int)
  (batchCount :int))

(cl:export 'cublasCgemmBatched)

(cffi:defcfun ("cublasCgemm3mBatched" cublasCgemm3mBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (Aarray :pointer)
  (lda :int)
  (Barray :pointer)
  (ldb :int)
  (beta :pointer)
  (Carray :pointer)
  (ldc :int)
  (batchCount :int))

(cl:export 'cublasCgemm3mBatched)

(cffi:defcfun ("cublasZgemmBatched" cublasZgemmBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (Aarray :pointer)
  (lda :int)
  (Barray :pointer)
  (ldb :int)
  (beta :pointer)
  (Carray :pointer)
  (ldc :int)
  (batchCount :int))

(cl:export 'cublasZgemmBatched)

(cffi:defcfun ("cublasGemmBatchedEx" cublasGemmBatchedEx) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (Aarray :pointer)
  (Atype :pointer)
  (lda :int)
  (Barray :pointer)
  (Btype :pointer)
  (ldb :int)
  (beta :pointer)
  (Carray :pointer)
  (Ctype :pointer)
  (ldc :int)
  (batchCount :int)
  (computeType :pointer)
  (algo cublasGemmAlgo_t))

(cl:export 'cublasGemmBatchedEx)

(cffi:defcfun ("cublasGemmStridedBatchedEx" cublasGemmStridedBatchedEx) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (Atype :pointer)
  (lda :int)
  (strideA :long-long)
  (B :pointer)
  (Btype :pointer)
  (ldb :int)
  (strideB :long-long)
  (beta :pointer)
  (C :pointer)
  (Ctype :pointer)
  (ldc :int)
  (strideC :long-long)
  (batchCount :int)
  (computeType :pointer)
  (algo cublasGemmAlgo_t))

(cl:export 'cublasGemmStridedBatchedEx)

(cffi:defcfun ("cublasSgemmStridedBatched" cublasSgemmStridedBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (strideA :long-long)
  (B :pointer)
  (ldb :int)
  (strideB :long-long)
  (beta :pointer)
  (C :pointer)
  (ldc :int)
  (strideC :long-long)
  (batchCount :int))

(cl:export 'cublasSgemmStridedBatched)

(cffi:defcfun ("cublasDgemmStridedBatched" cublasDgemmStridedBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (strideA :long-long)
  (B :pointer)
  (ldb :int)
  (strideB :long-long)
  (beta :pointer)
  (C :pointer)
  (ldc :int)
  (strideC :long-long)
  (batchCount :int))

(cl:export 'cublasDgemmStridedBatched)

(cffi:defcfun ("cublasCgemmStridedBatched" cublasCgemmStridedBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (strideA :long-long)
  (B :pointer)
  (ldb :int)
  (strideB :long-long)
  (beta :pointer)
  (C :pointer)
  (ldc :int)
  (strideC :long-long)
  (batchCount :int))

(cl:export 'cublasCgemmStridedBatched)

(cffi:defcfun ("cublasCgemm3mStridedBatched" cublasCgemm3mStridedBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (strideA :long-long)
  (B :pointer)
  (ldb :int)
  (strideB :long-long)
  (beta :pointer)
  (C :pointer)
  (ldc :int)
  (strideC :long-long)
  (batchCount :int))

(cl:export 'cublasCgemm3mStridedBatched)

(cffi:defcfun ("cublasZgemmStridedBatched" cublasZgemmStridedBatched) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (k :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (strideA :long-long)
  (B :pointer)
  (ldb :int)
  (strideB :long-long)
  (beta :pointer)
  (C :pointer)
  (ldc :int)
  (strideC :long-long)
  (batchCount :int))

(cl:export 'cublasZgemmStridedBatched)

(cffi:defcfun ("cublasSgeam" cublasSgeam) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (B :pointer)
  (ldb :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSgeam)

(cffi:defcfun ("cublasDgeam" cublasDgeam) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (B :pointer)
  (ldb :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDgeam)

(cffi:defcfun ("cublasCgeam" cublasCgeam) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (B :pointer)
  (ldb :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCgeam)

(cffi:defcfun ("cublasZgeam" cublasZgeam) cublasStatus_t
  (handle :pointer)
  (transa cublasOperation_t)
  (transb cublasOperation_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (beta :pointer)
  (B :pointer)
  (ldb :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZgeam)

(cffi:defcfun ("cublasSgetrfBatched" cublasSgetrfBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (P :pointer)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasSgetrfBatched)

(cffi:defcfun ("cublasDgetrfBatched" cublasDgetrfBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (P :pointer)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasDgetrfBatched)

(cffi:defcfun ("cublasCgetrfBatched" cublasCgetrfBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (P :pointer)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasCgetrfBatched)

(cffi:defcfun ("cublasZgetrfBatched" cublasZgetrfBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (P :pointer)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasZgetrfBatched)

(cffi:defcfun ("cublasSgetriBatched" cublasSgetriBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (P :pointer)
  (C :pointer)
  (ldc :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasSgetriBatched)

(cffi:defcfun ("cublasDgetriBatched" cublasDgetriBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (P :pointer)
  (C :pointer)
  (ldc :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasDgetriBatched)

(cffi:defcfun ("cublasCgetriBatched" cublasCgetriBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (P :pointer)
  (C :pointer)
  (ldc :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasCgetriBatched)

(cffi:defcfun ("cublasZgetriBatched" cublasZgetriBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (P :pointer)
  (C :pointer)
  (ldc :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasZgetriBatched)

(cffi:defcfun ("cublasSgetrsBatched" cublasSgetrsBatched) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (n :int)
  (nrhs :int)
  (Aarray :pointer)
  (lda :int)
  (devIpiv :pointer)
  (Barray :pointer)
  (ldb :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasSgetrsBatched)

(cffi:defcfun ("cublasDgetrsBatched" cublasDgetrsBatched) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (n :int)
  (nrhs :int)
  (Aarray :pointer)
  (lda :int)
  (devIpiv :pointer)
  (Barray :pointer)
  (ldb :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasDgetrsBatched)

(cffi:defcfun ("cublasCgetrsBatched" cublasCgetrsBatched) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (n :int)
  (nrhs :int)
  (Aarray :pointer)
  (lda :int)
  (devIpiv :pointer)
  (Barray :pointer)
  (ldb :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasCgetrsBatched)

(cffi:defcfun ("cublasZgetrsBatched" cublasZgetrsBatched) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (n :int)
  (nrhs :int)
  (Aarray :pointer)
  (lda :int)
  (devIpiv :pointer)
  (Barray :pointer)
  (ldb :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasZgetrsBatched)

(cffi:defcfun ("cublasStrsmBatched" cublasStrsmBatched) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (batchCount :int))

(cl:export 'cublasStrsmBatched)

(cffi:defcfun ("cublasDtrsmBatched" cublasDtrsmBatched) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (batchCount :int))

(cl:export 'cublasDtrsmBatched)

(cffi:defcfun ("cublasCtrsmBatched" cublasCtrsmBatched) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (batchCount :int))

(cl:export 'cublasCtrsmBatched)

(cffi:defcfun ("cublasZtrsmBatched" cublasZtrsmBatched) cublasStatus_t
  (handle :pointer)
  (side cublasSideMode_t)
  (uplo cublasFillMode_t)
  (trans cublasOperation_t)
  (diag cublasDiagType_t)
  (m :int)
  (n :int)
  (alpha :pointer)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (batchCount :int))

(cl:export 'cublasZtrsmBatched)

(cffi:defcfun ("cublasSmatinvBatched" cublasSmatinvBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (Ainv :pointer)
  (lda_inv :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasSmatinvBatched)

(cffi:defcfun ("cublasDmatinvBatched" cublasDmatinvBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (Ainv :pointer)
  (lda_inv :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasDmatinvBatched)

(cffi:defcfun ("cublasCmatinvBatched" cublasCmatinvBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (Ainv :pointer)
  (lda_inv :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasCmatinvBatched)

(cffi:defcfun ("cublasZmatinvBatched" cublasZmatinvBatched) cublasStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (Ainv :pointer)
  (lda_inv :int)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasZmatinvBatched)

(cffi:defcfun ("cublasSgeqrfBatched" cublasSgeqrfBatched) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (Aarray :pointer)
  (lda :int)
  (TauArray :pointer)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasSgeqrfBatched)

(cffi:defcfun ("cublasDgeqrfBatched" cublasDgeqrfBatched) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (Aarray :pointer)
  (lda :int)
  (TauArray :pointer)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasDgeqrfBatched)

(cffi:defcfun ("cublasCgeqrfBatched" cublasCgeqrfBatched) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (Aarray :pointer)
  (lda :int)
  (TauArray :pointer)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasCgeqrfBatched)

(cffi:defcfun ("cublasZgeqrfBatched" cublasZgeqrfBatched) cublasStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (Aarray :pointer)
  (lda :int)
  (TauArray :pointer)
  (info :pointer)
  (batchSize :int))

(cl:export 'cublasZgeqrfBatched)

(cffi:defcfun ("cublasSgelsBatched" cublasSgelsBatched) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (nrhs :int)
  (Aarray :pointer)
  (lda :int)
  (Carray :pointer)
  (ldc :int)
  (info :pointer)
  (devInfoArray :pointer)
  (batchSize :int))

(cl:export 'cublasSgelsBatched)

(cffi:defcfun ("cublasDgelsBatched" cublasDgelsBatched) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (nrhs :int)
  (Aarray :pointer)
  (lda :int)
  (Carray :pointer)
  (ldc :int)
  (info :pointer)
  (devInfoArray :pointer)
  (batchSize :int))

(cl:export 'cublasDgelsBatched)

(cffi:defcfun ("cublasCgelsBatched" cublasCgelsBatched) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (nrhs :int)
  (Aarray :pointer)
  (lda :int)
  (Carray :pointer)
  (ldc :int)
  (info :pointer)
  (devInfoArray :pointer)
  (batchSize :int))

(cl:export 'cublasCgelsBatched)

(cffi:defcfun ("cublasZgelsBatched" cublasZgelsBatched) cublasStatus_t
  (handle :pointer)
  (trans cublasOperation_t)
  (m :int)
  (n :int)
  (nrhs :int)
  (Aarray :pointer)
  (lda :int)
  (Carray :pointer)
  (ldc :int)
  (info :pointer)
  (devInfoArray :pointer)
  (batchSize :int))

(cl:export 'cublasZgelsBatched)

(cffi:defcfun ("cublasSdgmm" cublasSdgmm) cublasStatus_t
  (handle :pointer)
  (mode cublasSideMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasSdgmm)

(cffi:defcfun ("cublasDdgmm" cublasDdgmm) cublasStatus_t
  (handle :pointer)
  (mode cublasSideMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasDdgmm)

(cffi:defcfun ("cublasCdgmm" cublasCdgmm) cublasStatus_t
  (handle :pointer)
  (mode cublasSideMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasCdgmm)

(cffi:defcfun ("cublasZdgmm" cublasZdgmm) cublasStatus_t
  (handle :pointer)
  (mode cublasSideMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (x :pointer)
  (incx :int)
  (C :pointer)
  (ldc :int))

(cl:export 'cublasZdgmm)

(cffi:defcfun ("cublasStpttr" cublasStpttr) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (AP :pointer)
  (A :pointer)
  (lda :int))

(cl:export 'cublasStpttr)

(cffi:defcfun ("cublasDtpttr" cublasDtpttr) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (AP :pointer)
  (A :pointer)
  (lda :int))

(cl:export 'cublasDtpttr)

(cffi:defcfun ("cublasCtpttr" cublasCtpttr) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (AP :pointer)
  (A :pointer)
  (lda :int))

(cl:export 'cublasCtpttr)

(cffi:defcfun ("cublasZtpttr" cublasZtpttr) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (AP :pointer)
  (A :pointer)
  (lda :int))

(cl:export 'cublasZtpttr)

(cffi:defcfun ("cublasStrttp" cublasStrttp) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (AP :pointer))

(cl:export 'cublasStrttp)

(cffi:defcfun ("cublasDtrttp" cublasDtrttp) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (AP :pointer))

(cl:export 'cublasDtrttp)

(cffi:defcfun ("cublasCtrttp" cublasCtrttp) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (AP :pointer))

(cl:export 'cublasCtrttp)

(cffi:defcfun ("cublasZtrttp" cublasZtrttp) cublasStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (AP :pointer))

(cl:export 'cublasZtrttp)


