;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


;;;SWIG wrapper code starts here
(in-package #:cl-matrix)

(cffi:defcenum cusolverStatus_t
	(:CUSOLVER_STATUS_SUCCESS #.0)
	(:CUSOLVER_STATUS_NOT_INITIALIZED #.1)
	(:CUSOLVER_STATUS_ALLOC_FAILED #.2)
	(:CUSOLVER_STATUS_INVALID_VALUE #.3)
	(:CUSOLVER_STATUS_ARCH_MISMATCH #.4)
	(:CUSOLVER_STATUS_MAPPING_ERROR #.5)
	(:CUSOLVER_STATUS_EXECUTION_FAILED #.6)
	(:CUSOLVER_STATUS_INTERNAL_ERROR #.7)
	(:CUSOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED #.8)
	(:CUSOLVER_STATUS_NOT_SUPPORTED #.9)
	(:CUSOLVER_STATUS_ZERO_PIVOT #.10)
	(:CUSOLVER_STATUS_INVALID_LICENSE #.11))

(cl:export 'cusolverStatus_t)

(cffi:defcenum cusolverEigType_t
	(:CUSOLVER_EIG_TYPE_1 #.1)
	(:CUSOLVER_EIG_TYPE_2 #.2)
	(:CUSOLVER_EIG_TYPE_3 #.3))

(cl:export 'cusolverEigType_t)

(cffi:defcenum cusolverEigMode_t
	(:CUSOLVER_EIG_MODE_NOVECTOR #.0)
	(:CUSOLVER_EIG_MODE_VECTOR #.1))

(cl:export 'cusolverEigMode_t)

(cffi:defcfun ("cusolverGetProperty" cusolverGetProperty) cusolverStatus_t
  (type :pointer)
  (value :pointer))

(cl:export 'cusolverGetProperty)

(cffi:defcfun ("cusolverDnCreate" cusolverDnCreate) cusolverStatus_t
  (handle :pointer))

(cl:export 'cusolverDnCreate)

(cffi:defcfun ("cusolverDnDestroy" cusolverDnDestroy) cusolverStatus_t
  (handle :pointer))

(cl:export 'cusolverDnDestroy)

(cffi:defcfun ("cusolverDnSetStream" cusolverDnSetStream) cusolverStatus_t
  (handle :pointer)
  (streamId :pointer))

(cl:export 'cusolverDnSetStream)

(cffi:defcfun ("cusolverDnGetStream" cusolverDnGetStream) cusolverStatus_t
  (handle :pointer)
  (streamId :pointer))

(cl:export 'cusolverDnGetStream)

(cffi:defcfun ("cusolverDnSpotrf_bufferSize" cusolverDnSpotrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (Lwork :pointer))

(cl:export 'cusolverDnSpotrf_bufferSize)

(cffi:defcfun ("cusolverDnDpotrf_bufferSize" cusolverDnDpotrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (Lwork :pointer))

(cl:export 'cusolverDnDpotrf_bufferSize)

(cffi:defcfun ("cusolverDnCpotrf_bufferSize" cusolverDnCpotrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (Lwork :pointer))

(cl:export 'cusolverDnCpotrf_bufferSize)

(cffi:defcfun ("cusolverDnZpotrf_bufferSize" cusolverDnZpotrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (Lwork :pointer))

(cl:export 'cusolverDnZpotrf_bufferSize)

(cffi:defcfun ("cusolverDnSpotrf" cusolverDnSpotrf) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (Workspace :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnSpotrf)

(cffi:defcfun ("cusolverDnDpotrf" cusolverDnDpotrf) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (Workspace :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnDpotrf)

(cffi:defcfun ("cusolverDnCpotrf" cusolverDnCpotrf) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (Workspace :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnCpotrf)

(cffi:defcfun ("cusolverDnZpotrf" cusolverDnZpotrf) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (Workspace :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnZpotrf)

(cffi:defcfun ("cusolverDnSpotrs" cusolverDnSpotrs) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (devInfo :pointer))

(cl:export 'cusolverDnSpotrs)

(cffi:defcfun ("cusolverDnDpotrs" cusolverDnDpotrs) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (devInfo :pointer))

(cl:export 'cusolverDnDpotrs)

(cffi:defcfun ("cusolverDnCpotrs" cusolverDnCpotrs) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (devInfo :pointer))

(cl:export 'cusolverDnCpotrs)

(cffi:defcfun ("cusolverDnZpotrs" cusolverDnZpotrs) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (devInfo :pointer))

(cl:export 'cusolverDnZpotrs)

(cffi:defcfun ("cusolverDnSpotrfBatched" cusolverDnSpotrfBatched) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (Aarray :pointer)
  (lda :int)
  (infoArray :pointer)
  (batchSize :int))

(cl:export 'cusolverDnSpotrfBatched)

(cffi:defcfun ("cusolverDnDpotrfBatched" cusolverDnDpotrfBatched) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (Aarray :pointer)
  (lda :int)
  (infoArray :pointer)
  (batchSize :int))

(cl:export 'cusolverDnDpotrfBatched)

(cffi:defcfun ("cusolverDnCpotrfBatched" cusolverDnCpotrfBatched) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (Aarray :pointer)
  (lda :int)
  (infoArray :pointer)
  (batchSize :int))

(cl:export 'cusolverDnCpotrfBatched)

(cffi:defcfun ("cusolverDnZpotrfBatched" cusolverDnZpotrfBatched) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (Aarray :pointer)
  (lda :int)
  (infoArray :pointer)
  (batchSize :int))

(cl:export 'cusolverDnZpotrfBatched)

(cffi:defcfun ("cusolverDnSpotrsBatched" cusolverDnSpotrsBatched) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (d_info :pointer)
  (batchSize :int))

(cl:export 'cusolverDnSpotrsBatched)

(cffi:defcfun ("cusolverDnDpotrsBatched" cusolverDnDpotrsBatched) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (d_info :pointer)
  (batchSize :int))

(cl:export 'cusolverDnDpotrsBatched)

(cffi:defcfun ("cusolverDnCpotrsBatched" cusolverDnCpotrsBatched) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (d_info :pointer)
  (batchSize :int))

(cl:export 'cusolverDnCpotrsBatched)

(cffi:defcfun ("cusolverDnZpotrsBatched" cusolverDnZpotrsBatched) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (d_info :pointer)
  (batchSize :int))

(cl:export 'cusolverDnZpotrsBatched)

(cffi:defcfun ("cusolverDnSgetrf_bufferSize" cusolverDnSgetrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (Lwork :pointer))

(cl:export 'cusolverDnSgetrf_bufferSize)

(cffi:defcfun ("cusolverDnDgetrf_bufferSize" cusolverDnDgetrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (Lwork :pointer))

(cl:export 'cusolverDnDgetrf_bufferSize)

(cffi:defcfun ("cusolverDnCgetrf_bufferSize" cusolverDnCgetrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (Lwork :pointer))

(cl:export 'cusolverDnCgetrf_bufferSize)

(cffi:defcfun ("cusolverDnZgetrf_bufferSize" cusolverDnZgetrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (Lwork :pointer))

(cl:export 'cusolverDnZgetrf_bufferSize)

(cffi:defcfun ("cusolverDnSgetrf" cusolverDnSgetrf) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (Workspace :pointer)
  (devIpiv :pointer)
  (devInfo :pointer))

(cl:export 'cusolverDnSgetrf)

(cffi:defcfun ("cusolverDnDgetrf" cusolverDnDgetrf) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (Workspace :pointer)
  (devIpiv :pointer)
  (devInfo :pointer))

(cl:export 'cusolverDnDgetrf)

(cffi:defcfun ("cusolverDnCgetrf" cusolverDnCgetrf) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (Workspace :pointer)
  (devIpiv :pointer)
  (devInfo :pointer))

(cl:export 'cusolverDnCgetrf)

(cffi:defcfun ("cusolverDnZgetrf" cusolverDnZgetrf) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (Workspace :pointer)
  (devIpiv :pointer)
  (devInfo :pointer))

(cl:export 'cusolverDnZgetrf)

(cffi:defcfun ("cusolverDnSlaswp" cusolverDnSlaswp) cusolverStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (k1 :int)
  (k2 :int)
  (devIpiv :pointer)
  (incx :int))

(cl:export 'cusolverDnSlaswp)

(cffi:defcfun ("cusolverDnDlaswp" cusolverDnDlaswp) cusolverStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (k1 :int)
  (k2 :int)
  (devIpiv :pointer)
  (incx :int))

(cl:export 'cusolverDnDlaswp)

(cffi:defcfun ("cusolverDnClaswp" cusolverDnClaswp) cusolverStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (k1 :int)
  (k2 :int)
  (devIpiv :pointer)
  (incx :int))

(cl:export 'cusolverDnClaswp)

(cffi:defcfun ("cusolverDnZlaswp" cusolverDnZlaswp) cusolverStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (k1 :int)
  (k2 :int)
  (devIpiv :pointer)
  (incx :int))

(cl:export 'cusolverDnZlaswp)

(cffi:defcfun ("cusolverDnSgetrs" cusolverDnSgetrs) cusolverStatus_t
  (handle :pointer)
  (trans  cublasoperation_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (devIpiv :pointer)
  (B :pointer)
  (ldb :int)
  (devInfo :pointer))

(cl:export 'cusolverDnSgetrs)

(cffi:defcfun ("cusolverDnDgetrs" cusolverDnDgetrs) cusolverStatus_t
  (handle :pointer)
  (trans  cublasoperation_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (devIpiv :pointer)
  (B :pointer)
  (ldb :int)
  (devInfo :pointer))

(cl:export 'cusolverDnDgetrs)

(cffi:defcfun ("cusolverDnCgetrs" cusolverDnCgetrs) cusolverStatus_t
  (handle :pointer)
  (trans cublasoperation_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (devIpiv :pointer)
  (B :pointer)
  (ldb :int)
  (devInfo :pointer))

(cl:export 'cusolverDnCgetrs)

(cffi:defcfun ("cusolverDnZgetrs" cusolverDnZgetrs) cusolverStatus_t
  (handle :pointer)
  (trans cublasoperation_t)
  (n :int)
  (nrhs :int)
  (A :pointer)
  (lda :int)
  (devIpiv :pointer)
  (B :pointer)
  (ldb :int)
  (devInfo :pointer))

(cl:export 'cusolverDnZgetrs)

(cffi:defcfun ("cusolverDnSgeqrf_bufferSize" cusolverDnSgeqrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (lwork :pointer))

(cl:export 'cusolverDnSgeqrf_bufferSize)

(cffi:defcfun ("cusolverDnDgeqrf_bufferSize" cusolverDnDgeqrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (lwork :pointer))

(cl:export 'cusolverDnDgeqrf_bufferSize)

(cffi:defcfun ("cusolverDnCgeqrf_bufferSize" cusolverDnCgeqrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (lwork :pointer))

(cl:export 'cusolverDnCgeqrf_bufferSize)

(cffi:defcfun ("cusolverDnZgeqrf_bufferSize" cusolverDnZgeqrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (lwork :pointer))

(cl:export 'cusolverDnZgeqrf_bufferSize)

(cffi:defcfun ("cusolverDnSgeqrf" cusolverDnSgeqrf) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (TAU :pointer)
  (Workspace :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnSgeqrf)

(cffi:defcfun ("cusolverDnDgeqrf" cusolverDnDgeqrf) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (TAU :pointer)
  (Workspace :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnDgeqrf)

(cffi:defcfun ("cusolverDnCgeqrf" cusolverDnCgeqrf) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (TAU :pointer)
  (Workspace :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnCgeqrf)

(cffi:defcfun ("cusolverDnZgeqrf" cusolverDnZgeqrf) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (TAU :pointer)
  (Workspace :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnZgeqrf)

(cffi:defcfun ("cusolverDnSorgqr_bufferSize" cusolverDnSorgqr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnSorgqr_bufferSize)

(cffi:defcfun ("cusolverDnDorgqr_bufferSize" cusolverDnDorgqr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnDorgqr_bufferSize)

(cffi:defcfun ("cusolverDnCungqr_bufferSize" cusolverDnCungqr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnCungqr_bufferSize)

(cffi:defcfun ("cusolverDnZungqr_bufferSize" cusolverDnZungqr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnZungqr_bufferSize)

(cffi:defcfun ("cusolverDnSorgqr" cusolverDnSorgqr) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnSorgqr)

(cffi:defcfun ("cusolverDnDorgqr" cusolverDnDorgqr) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnDorgqr)

(cffi:defcfun ("cusolverDnCungqr" cusolverDnCungqr) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnCungqr)

(cffi:defcfun ("cusolverDnZungqr" cusolverDnZungqr) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnZungqr)

(cffi:defcfun ("cusolverDnSormqr_bufferSize" cusolverDnSormqr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (trans :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (lwork :pointer))

(cl:export 'cusolverDnSormqr_bufferSize)

(cffi:defcfun ("cusolverDnDormqr_bufferSize" cusolverDnDormqr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (trans :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (lwork :pointer))

(cl:export 'cusolverDnDormqr_bufferSize)

(cffi:defcfun ("cusolverDnCunmqr_bufferSize" cusolverDnCunmqr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (trans :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (lwork :pointer))

(cl:export 'cusolverDnCunmqr_bufferSize)

(cffi:defcfun ("cusolverDnZunmqr_bufferSize" cusolverDnZunmqr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (trans :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (lwork :pointer))

(cl:export 'cusolverDnZunmqr_bufferSize)

(cffi:defcfun ("cusolverDnSormqr" cusolverDnSormqr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (trans :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (work :pointer)
  (lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnSormqr)

(cffi:defcfun ("cusolverDnDormqr" cusolverDnDormqr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (trans :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (work :pointer)
  (lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnDormqr)

(cffi:defcfun ("cusolverDnCunmqr" cusolverDnCunmqr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (trans :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (work :pointer)
  (lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnCunmqr)

(cffi:defcfun ("cusolverDnZunmqr" cusolverDnZunmqr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (trans :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (work :pointer)
  (lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnZunmqr)

(cffi:defcfun ("cusolverDnSsytrf_bufferSize" cusolverDnSsytrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (lwork :pointer))

(cl:export 'cusolverDnSsytrf_bufferSize)

(cffi:defcfun ("cusolverDnDsytrf_bufferSize" cusolverDnDsytrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (lwork :pointer))

(cl:export 'cusolverDnDsytrf_bufferSize)

(cffi:defcfun ("cusolverDnCsytrf_bufferSize" cusolverDnCsytrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (lwork :pointer))

(cl:export 'cusolverDnCsytrf_bufferSize)

(cffi:defcfun ("cusolverDnZsytrf_bufferSize" cusolverDnZsytrf_bufferSize) cusolverStatus_t
  (handle :pointer)
  (n :int)
  (A :pointer)
  (lda :int)
  (lwork :pointer))

(cl:export 'cusolverDnZsytrf_bufferSize)

(cffi:defcfun ("cusolverDnSsytrf" cusolverDnSsytrf) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (ipiv :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnSsytrf)

(cffi:defcfun ("cusolverDnDsytrf" cusolverDnDsytrf) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (ipiv :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnDsytrf)

(cffi:defcfun ("cusolverDnCsytrf" cusolverDnCsytrf) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (ipiv :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnCsytrf)

(cffi:defcfun ("cusolverDnZsytrf" cusolverDnZsytrf) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (ipiv :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnZsytrf)

(cffi:defcfun ("cusolverDnSgebrd_bufferSize" cusolverDnSgebrd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (Lwork :pointer))

(cl:export 'cusolverDnSgebrd_bufferSize)

(cffi:defcfun ("cusolverDnDgebrd_bufferSize" cusolverDnDgebrd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (Lwork :pointer))

(cl:export 'cusolverDnDgebrd_bufferSize)

(cffi:defcfun ("cusolverDnCgebrd_bufferSize" cusolverDnCgebrd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (Lwork :pointer))

(cl:export 'cusolverDnCgebrd_bufferSize)

(cffi:defcfun ("cusolverDnZgebrd_bufferSize" cusolverDnZgebrd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (Lwork :pointer))

(cl:export 'cusolverDnZgebrd_bufferSize)

(cffi:defcfun ("cusolverDnSgebrd" cusolverDnSgebrd) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (D :pointer)
  (E :pointer)
  (TAUQ :pointer)
  (TAUP :pointer)
  (Work :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnSgebrd)

(cffi:defcfun ("cusolverDnDgebrd" cusolverDnDgebrd) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (D :pointer)
  (E :pointer)
  (TAUQ :pointer)
  (TAUP :pointer)
  (Work :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnDgebrd)

(cffi:defcfun ("cusolverDnCgebrd" cusolverDnCgebrd) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (D :pointer)
  (E :pointer)
  (TAUQ :pointer)
  (TAUP :pointer)
  (Work :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnCgebrd)

(cffi:defcfun ("cusolverDnZgebrd" cusolverDnZgebrd) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (D :pointer)
  (E :pointer)
  (TAUQ :pointer)
  (TAUP :pointer)
  (Work :pointer)
  (Lwork :int)
  (devInfo :pointer))

(cl:export 'cusolverDnZgebrd)

(cffi:defcfun ("cusolverDnSorgbr_bufferSize" cusolverDnSorgbr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnSorgbr_bufferSize)

(cffi:defcfun ("cusolverDnDorgbr_bufferSize" cusolverDnDorgbr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnDorgbr_bufferSize)

(cffi:defcfun ("cusolverDnCungbr_bufferSize" cusolverDnCungbr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnCungbr_bufferSize)

(cffi:defcfun ("cusolverDnZungbr_bufferSize" cusolverDnZungbr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnZungbr_bufferSize)

(cffi:defcfun ("cusolverDnSorgbr" cusolverDnSorgbr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnSorgbr)

(cffi:defcfun ("cusolverDnDorgbr" cusolverDnDorgbr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnDorgbr)

(cffi:defcfun ("cusolverDnCungbr" cusolverDnCungbr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnCungbr)

(cffi:defcfun ("cusolverDnZungbr" cusolverDnZungbr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (m :int)
  (n :int)
  (k :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnZungbr)

(cffi:defcfun ("cusolverDnSsytrd_bufferSize" cusolverDnSsytrd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (d :pointer)
  (e :pointer)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnSsytrd_bufferSize)

(cffi:defcfun ("cusolverDnDsytrd_bufferSize" cusolverDnDsytrd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (d :pointer)
  (e :pointer)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnDsytrd_bufferSize)

(cffi:defcfun ("cusolverDnChetrd_bufferSize" cusolverDnChetrd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (d :pointer)
  (e :pointer)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnChetrd_bufferSize)

(cffi:defcfun ("cusolverDnZhetrd_bufferSize" cusolverDnZhetrd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (d :pointer)
  (e :pointer)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnZhetrd_bufferSize)

(cffi:defcfun ("cusolverDnSsytrd" cusolverDnSsytrd) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (d :pointer)
  (e :pointer)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnSsytrd)

(cffi:defcfun ("cusolverDnDsytrd" cusolverDnDsytrd) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (d :pointer)
  (e :pointer)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnDsytrd)

(cffi:defcfun ("cusolverDnChetrd" cusolverDnChetrd) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (d :pointer)
  (e :pointer)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnChetrd)

(cffi:defcfun ("cusolverDnZhetrd" cusolverDnZhetrd) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (d :pointer)
  (e :pointer)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnZhetrd)

(cffi:defcfun ("cusolverDnSorgtr_bufferSize" cusolverDnSorgtr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnSorgtr_bufferSize)

(cffi:defcfun ("cusolverDnDorgtr_bufferSize" cusolverDnDorgtr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnDorgtr_bufferSize)

(cffi:defcfun ("cusolverDnCungtr_bufferSize" cusolverDnCungtr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnCungtr_bufferSize)

(cffi:defcfun ("cusolverDnZungtr_bufferSize" cusolverDnZungtr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnZungtr_bufferSize)

(cffi:defcfun ("cusolverDnSorgtr" cusolverDnSorgtr) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnSorgtr)

(cffi:defcfun ("cusolverDnDorgtr" cusolverDnDorgtr) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnDorgtr)

(cffi:defcfun ("cusolverDnCungtr" cusolverDnCungtr) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnCungtr)

(cffi:defcfun ("cusolverDnZungtr" cusolverDnZungtr) cusolverStatus_t
  (handle :pointer)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnZungtr)

(cffi:defcfun ("cusolverDnSormtr_bufferSize" cusolverDnSormtr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (uplo cublasFillMode_t)
  (trans :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (lwork :pointer))

(cl:export 'cusolverDnSormtr_bufferSize)

(cffi:defcfun ("cusolverDnDormtr_bufferSize" cusolverDnDormtr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (uplo cublasFillMode_t)
  (trans :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (lwork :pointer))

(cl:export 'cusolverDnDormtr_bufferSize)

(cffi:defcfun ("cusolverDnCunmtr_bufferSize" cusolverDnCunmtr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (uplo cublasFillMode_t)
  (trans :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (lwork :pointer))

(cl:export 'cusolverDnCunmtr_bufferSize)

(cffi:defcfun ("cusolverDnZunmtr_bufferSize" cusolverDnZunmtr_bufferSize) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (uplo cublasFillMode_t)
  (trans :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (lwork :pointer))

(cl:export 'cusolverDnZunmtr_bufferSize)

(cffi:defcfun ("cusolverDnSormtr" cusolverDnSormtr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (uplo cublasFillMode_t)
  (trans :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnSormtr)

(cffi:defcfun ("cusolverDnDormtr" cusolverDnDormtr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (uplo cublasFillMode_t)
  (trans :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnDormtr)

(cffi:defcfun ("cusolverDnCunmtr" cusolverDnCunmtr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (uplo cublasFillMode_t)
  (trans :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnCunmtr)

(cffi:defcfun ("cusolverDnZunmtr" cusolverDnZunmtr) cusolverStatus_t
  (handle :pointer)
  (side :pointer)
  (uplo cublasFillMode_t)
  (trans :pointer)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (tau :pointer)
  (C :pointer)
  (ldc :int)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnZunmtr)

(cffi:defcfun ("cusolverDnSgesvd_bufferSize" cusolverDnSgesvd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (lwork :pointer))

(cl:export 'cusolverDnSgesvd_bufferSize)

(cffi:defcfun ("cusolverDnDgesvd_bufferSize" cusolverDnDgesvd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (lwork :pointer))

(cl:export 'cusolverDnDgesvd_bufferSize)

(cffi:defcfun ("cusolverDnCgesvd_bufferSize" cusolverDnCgesvd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (lwork :pointer))

(cl:export 'cusolverDnCgesvd_bufferSize)

(cffi:defcfun ("cusolverDnZgesvd_bufferSize" cusolverDnZgesvd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (m :int)
  (n :int)
  (lwork :pointer))

(cl:export 'cusolverDnZgesvd_bufferSize)

(cffi:defcfun ("cusolverDnSgesvd" cusolverDnSgesvd) cusolverStatus_t
  (handle :pointer)
  (jobu :char)
  (jobvt :char)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (VT :pointer)
  (ldvt :int)
  (work :pointer)
  (lwork :int)
  (rwork :pointer)
  (info :pointer))

(cl:export 'cusolverDnSgesvd)

(cffi:defcfun ("cusolverDnDgesvd" cusolverDnDgesvd) cusolverStatus_t
  (handle :pointer)
  (jobu :char)
  (jobvt :char)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (VT :pointer)
  (ldvt :int)
  (work :pointer)
  (lwork :int)
  (rwork :pointer)
  (info :pointer))

(cl:export 'cusolverDnDgesvd)

(cffi:defcfun ("cusolverDnCgesvd" cusolverDnCgesvd) cusolverStatus_t
  (handle :pointer)
  (jobu :char)
  (jobvt :char)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (VT :pointer)
  (ldvt :int)
  (work :pointer)
  (lwork :int)
  (rwork :pointer)
  (info :pointer))

(cl:export 'cusolverDnCgesvd)

(cffi:defcfun ("cusolverDnZgesvd" cusolverDnZgesvd) cusolverStatus_t
  (handle :pointer)
  (jobu :char)
  (jobvt :char)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (VT :pointer)
  (ldvt :int)
  (work :pointer)
  (lwork :int)
  (rwork :pointer)
  (info :pointer))

(cl:export 'cusolverDnZgesvd)

(cffi:defcfun ("cusolverDnSsyevd_bufferSize" cusolverDnSsyevd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnSsyevd_bufferSize)

(cffi:defcfun ("cusolverDnDsyevd_bufferSize" cusolverDnDsyevd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnDsyevd_bufferSize)

(cffi:defcfun ("cusolverDnCheevd_bufferSize" cusolverDnCheevd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnCheevd_bufferSize)

(cffi:defcfun ("cusolverDnZheevd_bufferSize" cusolverDnZheevd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnZheevd_bufferSize)

(cffi:defcfun ("cusolverDnSsyevd" cusolverDnSsyevd) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnSsyevd)

(cffi:defcfun ("cusolverDnDsyevd" cusolverDnDsyevd) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnDsyevd)

(cffi:defcfun ("cusolverDnCheevd" cusolverDnCheevd) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnCheevd)

(cffi:defcfun ("cusolverDnZheevd" cusolverDnZheevd) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnZheevd)

(cffi:defcfun ("cusolverDnSsygvd_bufferSize" cusolverDnSsygvd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnSsygvd_bufferSize)

(cffi:defcfun ("cusolverDnDsygvd_bufferSize" cusolverDnDsygvd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnDsygvd_bufferSize)

(cffi:defcfun ("cusolverDnChegvd_bufferSize" cusolverDnChegvd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnChegvd_bufferSize)

(cffi:defcfun ("cusolverDnZhegvd_bufferSize" cusolverDnZhegvd_bufferSize) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (lwork :pointer))

(cl:export 'cusolverDnZhegvd_bufferSize)

(cffi:defcfun ("cusolverDnSsygvd" cusolverDnSsygvd) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnSsygvd)

(cffi:defcfun ("cusolverDnDsygvd" cusolverDnDsygvd) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnDsygvd)

(cffi:defcfun ("cusolverDnChegvd" cusolverDnChegvd) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnChegvd)

(cffi:defcfun ("cusolverDnZhegvd" cusolverDnZhegvd) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer))

(cl:export 'cusolverDnZhegvd)

(cffi:defcfun ("cusolverDnCreateSyevjInfo" cusolverDnCreateSyevjInfo) cusolverStatus_t
  (info :pointer))

(cl:export 'cusolverDnCreateSyevjInfo)

(cffi:defcfun ("cusolverDnDestroySyevjInfo" cusolverDnDestroySyevjInfo) cusolverStatus_t
  (info :pointer))

(cl:export 'cusolverDnDestroySyevjInfo)

(cffi:defcfun ("cusolverDnXsyevjSetTolerance" cusolverDnXsyevjSetTolerance) cusolverStatus_t
  (info :pointer)
  (tolerance :double))

(cl:export 'cusolverDnXsyevjSetTolerance)

(cffi:defcfun ("cusolverDnXsyevjSetMaxSweeps" cusolverDnXsyevjSetMaxSweeps) cusolverStatus_t
  (info :pointer)
  (max_sweeps :int))

(cl:export 'cusolverDnXsyevjSetMaxSweeps)

(cffi:defcfun ("cusolverDnXsyevjSetSortEig" cusolverDnXsyevjSetSortEig) cusolverStatus_t
  (info :pointer)
  (sort_eig :int))

(cl:export 'cusolverDnXsyevjSetSortEig)

(cffi:defcfun ("cusolverDnXsyevjGetResidual" cusolverDnXsyevjGetResidual) cusolverStatus_t
  (handle :pointer)
  (info :pointer)
  (residual :pointer))

(cl:export 'cusolverDnXsyevjGetResidual)

(cffi:defcfun ("cusolverDnXsyevjGetSweeps" cusolverDnXsyevjGetSweeps) cusolverStatus_t
  (handle :pointer)
  (info :pointer)
  (executed_sweeps :pointer))

(cl:export 'cusolverDnXsyevjGetSweeps)

(cffi:defcfun ("cusolverDnSsyevjBatched_bufferSize" cusolverDnSsyevjBatched_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnSsyevjBatched_bufferSize)

(cffi:defcfun ("cusolverDnDsyevjBatched_bufferSize" cusolverDnDsyevjBatched_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnDsyevjBatched_bufferSize)

(cffi:defcfun ("cusolverDnCheevjBatched_bufferSize" cusolverDnCheevjBatched_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnCheevjBatched_bufferSize)

(cffi:defcfun ("cusolverDnZheevjBatched_bufferSize" cusolverDnZheevjBatched_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnZheevjBatched_bufferSize)

(cffi:defcfun ("cusolverDnSsyevjBatched" cusolverDnSsyevjBatched) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnSsyevjBatched)

(cffi:defcfun ("cusolverDnDsyevjBatched" cusolverDnDsyevjBatched) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnDsyevjBatched)

(cffi:defcfun ("cusolverDnCheevjBatched" cusolverDnCheevjBatched) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnCheevjBatched)

(cffi:defcfun ("cusolverDnZheevjBatched" cusolverDnZheevjBatched) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnZheevjBatched)

(cffi:defcfun ("cusolverDnSsyevj_bufferSize" cusolverDnSsyevj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnSsyevj_bufferSize)

(cffi:defcfun ("cusolverDnDsyevj_bufferSize" cusolverDnDsyevj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnDsyevj_bufferSize)

(cffi:defcfun ("cusolverDnCheevj_bufferSize" cusolverDnCheevj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnCheevj_bufferSize)

(cffi:defcfun ("cusolverDnZheevj_bufferSize" cusolverDnZheevj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnZheevj_bufferSize)

(cffi:defcfun ("cusolverDnSsyevj" cusolverDnSsyevj) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnSsyevj)

(cffi:defcfun ("cusolverDnDsyevj" cusolverDnDsyevj) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnDsyevj)

(cffi:defcfun ("cusolverDnCheevj" cusolverDnCheevj) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnCheevj)

(cffi:defcfun ("cusolverDnZheevj" cusolverDnZheevj) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnZheevj)

(cffi:defcfun ("cusolverDnSsygvj_bufferSize" cusolverDnSsygvj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnSsygvj_bufferSize)

(cffi:defcfun ("cusolverDnDsygvj_bufferSize" cusolverDnDsygvj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnDsygvj_bufferSize)

(cffi:defcfun ("cusolverDnChegvj_bufferSize" cusolverDnChegvj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnChegvj_bufferSize)

(cffi:defcfun ("cusolverDnZhegvj_bufferSize" cusolverDnZhegvj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnZhegvj_bufferSize)

(cffi:defcfun ("cusolverDnSsygvj" cusolverDnSsygvj) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnSsygvj)

(cffi:defcfun ("cusolverDnDsygvj" cusolverDnDsygvj) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnDsygvj)

(cffi:defcfun ("cusolverDnChegvj" cusolverDnChegvj) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnChegvj)

(cffi:defcfun ("cusolverDnZhegvj" cusolverDnZhegvj) cusolverStatus_t
  (handle :pointer)
  (itype cusolverEigType_t)
  (jobz cusolverEigMode_t)
  (uplo cublasFillMode_t)
  (n :int)
  (A :pointer)
  (lda :int)
  (B :pointer)
  (ldb :int)
  (W :pointer)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnZhegvj)

(cffi:defcfun ("cusolverDnCreateGesvdjInfo" cusolverDnCreateGesvdjInfo) cusolverStatus_t
  (info :pointer))

(cl:export 'cusolverDnCreateGesvdjInfo)

(cffi:defcfun ("cusolverDnDestroyGesvdjInfo" cusolverDnDestroyGesvdjInfo) cusolverStatus_t
  (info :pointer))

(cl:export 'cusolverDnDestroyGesvdjInfo)

(cffi:defcfun ("cusolverDnXgesvdjSetTolerance" cusolverDnXgesvdjSetTolerance) cusolverStatus_t
  (info :pointer)
  (tolerance :double))

(cl:export 'cusolverDnXgesvdjSetTolerance)

(cffi:defcfun ("cusolverDnXgesvdjSetMaxSweeps" cusolverDnXgesvdjSetMaxSweeps) cusolverStatus_t
  (info :pointer)
  (max_sweeps :int))

(cl:export 'cusolverDnXgesvdjSetMaxSweeps)

(cffi:defcfun ("cusolverDnXgesvdjSetSortEig" cusolverDnXgesvdjSetSortEig) cusolverStatus_t
  (info :pointer)
  (sort_svd :int))

(cl:export 'cusolverDnXgesvdjSetSortEig)

(cffi:defcfun ("cusolverDnXgesvdjGetResidual" cusolverDnXgesvdjGetResidual) cusolverStatus_t
  (handle :pointer)
  (info :pointer)
  (residual :pointer))

(cl:export 'cusolverDnXgesvdjGetResidual)

(cffi:defcfun ("cusolverDnXgesvdjGetSweeps" cusolverDnXgesvdjGetSweeps) cusolverStatus_t
  (handle :pointer)
  (info :pointer)
  (executed_sweeps :pointer))

(cl:export 'cusolverDnXgesvdjGetSweeps)

(cffi:defcfun ("cusolverDnSgesvdjBatched_bufferSize" cusolverDnSgesvdjBatched_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (lwork :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnSgesvdjBatched_bufferSize)

(cffi:defcfun ("cusolverDnDgesvdjBatched_bufferSize" cusolverDnDgesvdjBatched_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (lwork :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnDgesvdjBatched_bufferSize)

(cffi:defcfun ("cusolverDnCgesvdjBatched_bufferSize" cusolverDnCgesvdjBatched_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (lwork :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnCgesvdjBatched_bufferSize)

(cffi:defcfun ("cusolverDnZgesvdjBatched_bufferSize" cusolverDnZgesvdjBatched_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (lwork :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnZgesvdjBatched_bufferSize)

(cffi:defcfun ("cusolverDnSgesvdjBatched" cusolverDnSgesvdjBatched) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnSgesvdjBatched)

(cffi:defcfun ("cusolverDnDgesvdjBatched" cusolverDnDgesvdjBatched) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnDgesvdjBatched)

(cffi:defcfun ("cusolverDnCgesvdjBatched" cusolverDnCgesvdjBatched) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnCgesvdjBatched)

(cffi:defcfun ("cusolverDnZgesvdjBatched" cusolverDnZgesvdjBatched) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer)
  (batchSize :int))

(cl:export 'cusolverDnZgesvdjBatched)

(cffi:defcfun ("cusolverDnSgesvdj_bufferSize" cusolverDnSgesvdj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (econ :int)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnSgesvdj_bufferSize)

(cffi:defcfun ("cusolverDnDgesvdj_bufferSize" cusolverDnDgesvdj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (econ :int)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnDgesvdj_bufferSize)

(cffi:defcfun ("cusolverDnCgesvdj_bufferSize" cusolverDnCgesvdj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (econ :int)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnCgesvdj_bufferSize)

(cffi:defcfun ("cusolverDnZgesvdj_bufferSize" cusolverDnZgesvdj_bufferSize) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (econ :int)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (lwork :pointer)
  (params :pointer))

(cl:export 'cusolverDnZgesvdj_bufferSize)

(cffi:defcfun ("cusolverDnSgesvdj" cusolverDnSgesvdj) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (econ :int)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnSgesvdj)

(cffi:defcfun ("cusolverDnDgesvdj" cusolverDnDgesvdj) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (econ :int)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnDgesvdj)

(cffi:defcfun ("cusolverDnCgesvdj" cusolverDnCgesvdj) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (econ :int)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnCgesvdj)

(cffi:defcfun ("cusolverDnZgesvdj" cusolverDnZgesvdj) cusolverStatus_t
  (handle :pointer)
  (jobz cusolverEigMode_t)
  (econ :int)
  (m :int)
  (n :int)
  (A :pointer)
  (lda :int)
  (S :pointer)
  (U :pointer)
  (ldu :int)
  (V :pointer)
  (ldv :int)
  (work :pointer)
  (lwork :int)
  (info :pointer)
  (params :pointer))

(cl:export 'cusolverDnZgesvdj)


